import{a as i}from"./assets/vendor-a61d8330.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();i.defaults.headers.common["x-api-key"]="live_sqb8Cv5y2YS9Hf2WEqoZ7KDBAEFJ7Xw9Xi8579d7Bims2AvGILCcxRFdBYsTGXic";const c=document.querySelector(".cat-info"),a=document.querySelector(".loader"),u=document.querySelector(".error");function p(){return i.get("https://api.thecatapi.com/v1/breeds").then(t=>t).catch(t=>{throw new Error(t)})}function f(t){t.preventDefault();const o=t.target.value;return a.style.display="block",c.innerHTML="",i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${o}`).then(n=>{a.style.display="none";const s=n.data[0].breeds[0];c.style.display="flex",c.style.gap="20px",c.style.padding="20px 0",c.innerHTML=`<img src="${n.data[0].url}" alt="${s.name}" width='500' >
                <div>
                <h1>${s.name}</h1>
                <p>${s.description}</p>
                <p>Temperament: ${s.temperament}</p>
                </div>`}).catch(n=>{u.style.display="block"})}i.defaults.headers.common["x-api-key"]="live_sqb8Cv5y2YS9Hf2WEqoZ7KDBAEFJ7Xw9Xi8579d7Bims2AvGILCcxRFdBYsTGXic";const d=document.querySelector(".breed-select"),m=document.querySelector(".loader"),y=document.querySelector(".error");y.style.display="none";p().then(t=>{t.status===200&&(m.style.display="none",d.insertAdjacentHTML("beforeend",h(t.data)))}).catch(t=>console.log("Error!!!!",t));function h(t){return t.map(({id:o,name:n})=>`
    <option value="${o}">${n}</option>
    `).join("")}d.addEventListener("change",f);
//# sourceMappingURL=commonHelpers.js.map
